TrajectoryPlannerROS:
  max_vel_x: 0.45
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.1

  acc_lim_theta: 1
  acc_lim_x: 1
  acc_lim_y: 1

  holonomic_robot: true
  
  xy_goal_tolerance: 0.2              #default is 10cm but I think AMCL makes it too giggly for this to be safe
  yaw_goal_tolerance: 0.1             #default is 0.05 rad (~3 degrees)
  
  meter_scoring: true #Otherwise in grid cells 
