obstacle_range: 2.5 #Map updated with obstacles in 2.5 meters
raytrace_range: 3.0 #Range where we raytrace the free space
footprint: [[-0.3, -0.2], [-0.3, 0.2], [0.3, 0.2], [0.3 ,-0.2]]
#robot_radius: ir_of_robot
inflation_radius: 0.55

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo_link, data_type: LaserScan, topic: /canbot/laser/scan, marking: true, clearing: true}

